services:
  - type: web
    name: blogenhance
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import create_app; app = create_app(); app.app_context().push(); from app.models import db; db.create_all()"
      flask db stamp head
      flask db migrate
      flask db upgrade
    startCommand: gunicorn 'run:app' --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blogenhance-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_BASIC_PRICE_ID
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
      - key: STRIPE_ENTERPRISE_PRICE_ID
        sync: false

databases:
  - name: blogenhance-db
    plan: free 